package com.eworl.easybubble.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.eworl.easybubble.db.program;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PROGRAM".
*/
public class programDao extends AbstractDao<program, Long> {

    public static final String TABLENAME = "PROGRAM";

    /**
     * Properties of entity program.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AppName = new Property(1, String.class, "appName", false, "APP_NAME");
        public final static Property AppIcon = new Property(2, String.class, "appIcon", false, "APP_ICON");
        public final static Property GreenIcon = new Property(3, Integer.class, "greenIcon", false, "GREEN_ICON");
        public final static Property PlusIcon = new Property(4, Integer.class, "plusIcon", false, "PLUS_ICON");
        public final static Property PackageName = new Property(5, String.class, "packageName", false, "PACKAGE_NAME");
        public final static Property IsClicked = new Property(6, Boolean.class, "isClicked", false, "IS_CLICKED");
    };


    public programDao(DaoConfig config) {
        super(config);
    }
    
    public programDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PROGRAM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"APP_NAME\" TEXT," + // 1: appName
                "\"APP_ICON\" TEXT," + // 2: appIcon
                "\"GREEN_ICON\" INTEGER," + // 3: greenIcon
                "\"PLUS_ICON\" INTEGER," + // 4: plusIcon
                "\"PACKAGE_NAME\" TEXT UNIQUE ," + // 5: packageName
                "\"IS_CLICKED\" INTEGER);"); // 6: isClicked
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PROGRAM\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, program entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String appName = entity.getAppName();
        if (appName != null) {
            stmt.bindString(2, appName);
        }
 
        String appIcon = entity.getAppIcon();
        if (appIcon != null) {
            stmt.bindString(3, appIcon);
        }
 
        Integer greenIcon = entity.getGreenIcon();
        if (greenIcon != null) {
            stmt.bindLong(4, greenIcon);
        }
 
        Integer plusIcon = entity.getPlusIcon();
        if (plusIcon != null) {
            stmt.bindLong(5, plusIcon);
        }
 
        String packageName = entity.getPackageName();
        if (packageName != null) {
            stmt.bindString(6, packageName);
        }
 
        Boolean isClicked = entity.getIsClicked();
        if (isClicked != null) {
            stmt.bindLong(7, isClicked ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public program readEntity(Cursor cursor, int offset) {
        program entity = new program( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // appName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // appIcon
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // greenIcon
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // plusIcon
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // packageName
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0 // isClicked
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, program entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAppName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAppIcon(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGreenIcon(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setPlusIcon(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setPackageName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIsClicked(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(program entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(program entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
