package com.eworl.easybubble.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PROGRAM".
 */
public class program {

    private Long id;
    private String appName;
    private String appIcon;
    private Integer greenIcon;
    private Integer plusIcon;
    private String packageName;
    private Boolean isClicked;

    public program() {
    }

    public program(Long id) {
        this.id = id;
    }

    public program(Long id, String appName, String appIcon, Integer greenIcon, Integer plusIcon, String packageName, Boolean isClicked) {
        this.id = id;
        this.appName = appName;
        this.appIcon = appIcon;
        this.greenIcon = greenIcon;
        this.plusIcon = plusIcon;
        this.packageName = packageName;
        this.isClicked = isClicked;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getAppIcon() {
        return appIcon;
    }

    public void setAppIcon(String appIcon) {
        this.appIcon = appIcon;
    }

    public Integer getGreenIcon() {
        return greenIcon;
    }

    public void setGreenIcon(Integer greenIcon) {
        this.greenIcon = greenIcon;
    }

    public Integer getPlusIcon() {
        return plusIcon;
    }

    public void setPlusIcon(Integer plusIcon) {
        this.plusIcon = plusIcon;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public Boolean getIsClicked() {
        return isClicked;
    }

    public void setIsClicked(Boolean isClicked) {
        this.isClicked = isClicked;
    }

}
